#### CONFIGURACIÓN DE CONEXIÓN ####

url=jdbc:postgresql://postgres_liquibase:5432/liquibase_db
username=liquibase_user
password=liquibase_pass
driver=org.postgresql.Driver

#### RUTAS DE ARCHIVOS ####

changeLogFile=changelog-master.yaml
searchPath=/liquibase/changelog

#### DRIVER ####

classpath=/liquibase/changelog/drivers/postgresql-42.7.10.jar

#### LOGS ####
logLevel=info