changeLogFile=changelog-master.yaml

url=jdbc:postgresql://postgres_liquibase:5432/liquibase_db
username=liquibase_user
password=liquibase_pass
driver=org.postgresql.Driver

classpath=drivers/postgresql-42.7.3.jar